---
application: VTA Trip Planner
name: VTA Trip Planner
domain: vta.org

#announcements:

organization:
  name: VTA
  url: http://www.vta.org

# Application
version: 1.2.2

# Support Email Address
email:
  name: VTA Trip Planner Support
  address: tripplanner@vta.org

# Geocoding
geocode:
  center: -121.99905395507812,37.36197126180853
  zoom: 11
  start_address: 
  end_address: 

# Default application values
api_url: /api
base_url: http://tripplanner:5000

ignore_events_from: 'amigocloud.com'

# Google configuration
google_site_verification:
# Dev VTA OTP server key:
ga_key: ''


map_provider: 'GoogleV3'
#map_provider: 'ESRI'
#map_provider 'AmigoCloud'
#map_provider: 'Mapbox'

# AmigoCloud configuration
ac_key: ''
ac_event_url: ''
ac_event_table: ''
realtime_access_token: ''
realtime_dataset_url: ''
support_data_token: ''
bus_prediction_url: ''
bus_routes_url: ''
query_interval: 30000

feedback_table_name: ''
feedback_write_token: ''
feedback_write_url: ''

# Mapbox configuration
mapbox_access_token: ''
mapbox_map_id: ''

bing_key: ''


otp:
  host: otp
  path: /otp/routers/default
  port: 8888
s3_bucket: ''
segmentio_key: ''
static_url: /assets

# Custom Environments
environments:

  # For running tests
  test:
    google_api_key: ''
    google_geocode_api_key: ''
    bing_key: ''
    mapbox_access_token: ''
    mapbox_map_id: ''

  # Default & development
  development:
    google_api_key: ''
    google_geocode_api_key: ''
    bing_key: ''
    mapbox_access_token: ''
    mapbox_map_id: ''


  # Staging / QA / Production
  production:
    base_url:
    google_api_key: ''
    google_geocode_api_key: ''
    bing_key: ''
    mapbox_access_token: ''
    mapbox_map_id: ''
    google_site_verification:
    opsworks:
    node_app_id:
    otp_app_id:
    otp_layer_id:
    stack_id:
    s3_bucket:
    segmentio_key:
    static_url:
